version: '3.8'

services:
  pos-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pos-itq-frontend
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped