export interface INotaCreditoDetalle {
  idDetalleNotaCredito: number;
  idNotaCredito: number;
  registroNotaCredito: number;
  idDetalleVenta?: number | null;
  idProducto?: number | null;
  nombreProducto?: string | null;
  cantidadNotaCredito?: number | null;
  precioUnitarioNotaCredito?: number | null;
  precioTotalNotaCredito?: number | null;
  porcentajeDescuentoNotaCredito?: number | null;
  descuentoNotaCredito?: number | null;
  baseIvaNotaCredito?: number | null;
  porcentajeIvaNotaCredito?: number | null;
  ivaNotaCredito?: number | null;
  totalNotaCredito?: number | null;
  costoUnitarioNotaCredito?: number | null;
  costoTotalNotaCredito?: number | null;
  fechaGrabacionDetalleNotaCredito?: string | null;
  porcentajeRetelva?: number | null;
  baseRetelvaNotaCredito?: number | null;
  retelvaNotaCredito?: number | null;
  porcentajeReteRenta?: number | null;
  baseReteRenta?: number | null;
  reteRentaNotaCredito?: number | null;
  porcentajeRetelca?: number | null;
  baseRetelca?: number | null;
  retelcaNotaCredito?: number | null;
  idTerceroMandato?: number | null;
  idItemSector?: number | null;
  indicadorMuestra?: boolean | null;
  valorReferenciaUnidad?: number | null;
  valorReferenciaTotal?: number | null;
  codigoProducto?: string | null;
}