export interface IVentaDetalle {
  idDetalleVenta: number;
  idVenta: number;
  registroVenta: number;
  idProducto?: number | null;
  cantidadVenta?: number | null;
  precioUnitarioVenta?: number | null;
  precioTotalVenta?: number | null;
  porcentajeDescuentoVenta?: number | null;
  descuentoVenta?: number | null;
  porcentajeImpoConsumo?: number | null;
  impoConsumoVenta?: number | null;
  baseIvaVenta?: number | null;
  porcentajeIvaVenta?: number | null;
  ivaVenta?: number | null;
  totalVenta?: number | null;
  costoUnitarioVenta?: number | null;
  costoTotalVenta?: number | null;
  fechaGrabacionDetalleVenta?: string | Date | null;
  porcentajeReteIva?: number | null;
  baseReteIvaVenta?: number | null;
  reteIvaVenta?: number | null;
  porcentajeReteRenta?: number | null;
  baseReteRenta?: number | null;
  reteRentaVenta?: number | null;
  porcentajeReteIca?: number | null;
  baseReteIca?: number | null;
  reteIcaVenta?: number | null;
  nombreProducto?: string | null;
  idTerceroMandato?: number | null;
  idItemSector?: number | null;
  indicadorMuestra?: boolean | null;
  valorReferenciaUnidad?: number | null;
  valorReferenciaTotal?: number | null;

  codigoProducto?: string;
  idTipoProducto?: number;
  cantidadNotaCredito?: number;
  indNotaCredito?: boolean;
}