export interface IVentaDetalle {
    idDetalleVenta: number;
    registroVenta: number;
    idProducto: number;
    codigoProducto: string;
    nombreProducto: string;
    cantidadVenta: number;
    cantidadNotaCredito: number;
    indNotaCredito: boolean;
    precioUnitarioVenta: number;
    baseIvaVenta: number;
    porcentajeIvaVenta: number;
    ivaVenta: number;
    porcentajeDescuentoVenta: number;
    descuentoVenta: number;
    porcentajeImpoConsumo: number;
    impoConsumoVenta: number;
    porcentajeReteIva?: number | null;
    reteIvaVenta?: number | null;
    porcentajeReteRenta?: number | null;
    reteRentaVenta?: number | null;
    baseReteRenta?: number | null;
    porcentajeReteIca?: number | null;
    reteIcaVenta?: number | null;
    totalVenta?: number | null;
    costoUnitarioVenta?: number | null;
    costoTotalVenta?: number | null;   
    idTipoProducto: number;
    indicadorMuestra?: boolean | null;
}