import { IVentaDetalle } from "./IVentaDetalle";
import { IVentaMedioPago } from "./IVentaMedioPago";
import { IVentaTercero } from "./IVentaTercero";

export interface IVenta {
    idVenta: number;
    idTipoDocumento: number;
    idTipoDocumentoExterno?: number | null;
    codigoDocumento: string;
    nombreDocumento: string | null;
    idMetodoDian: number | null;
    idFormaPago: number | null;
    numeroVenta: number;
    prefijoVenta: string | null;
    idTerceroVenta?: number | null;
    fechaVenta: string | null;
    plazoDias?: number | null;
    fechaVencimiento?: string | null;
    esBorrador: boolean;
    idPuntoVenta: number | null;
    idUsuario: number | null;
    totalRegistros: number | null;
    cantidadProductos: number | null;
    totalPrecio: number | null;
    totalDescuento: number | null;
    totalBaseIva: number | null;
    totalIva: number | null;
    totalVenta: number | null;
    totalBaseReteIva?: number | null;
    totalReteIva?: number | null;
    totalBaseReteRenta?: number | null;
    totalReteRenta?: number | null;
    totalBaseReteIca?: number | null;
    totalReteIca?: number | null;
    estadoDian?: string | null;
    cufe?: string | null; 
    firmaDigital?: string | null; 
    fechaHoraAutorizacion?: string | null; 
    idResolucion?: number | null; 
    idResponseDian?: number | null; 
    idTipoOperacionDian?: number | null; 
    fechaGrabacionVenta?: string | null;
    observaciones: string | null;
    ordenReferencia: string | null;
    fechaOrdenReferencia: string | null;
    terceroVenta: IVentaTercero | null;
    detalleVenta: IVentaDetalle[] | null;
    mediosPagoVenta: IVentaMedioPago[] | null;
}